name: 'Release'
on:
  # Triggers the workflow on branch and tag creation events
  create:
jobs: 
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/release') }}
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Print github.ref
        run: |
          echo {{ github.ref }}
#         if: startsWith(github.ref, 'refs/tags/v*')
      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN}}
      - run: |
          cargo publish --allow-dirty
